### ISSUE TITLE
请教下

### ISSUE THREAD

**Issue by mhxy13867806343** [zymfe/calendar#1]
怎么根据后台给的月份，显示相关的数据
比如后台给的是9月 10月 11月 12月
就只要显示这 4个月的数据，其他月份看不到的，也就是
如下截图方式
![11111](https://user-images.githubusercontent.com/4418166/43730589-66b819d8-99de-11e8-96a6-b4790cb5921b.png)
麻烦了

**Comment by zhaoyiming0803** [comment]
1、后端给的数据哪年哪月开始（比如2018年9月）；
2、确定总共要显示N个月；
3、从开始月遍历N个月，每个月显示对应的那个月的数据就行。
4、我的这个日历，默认是从本年本月开始遍历，总共要遍历的月数，是可以传参确定的（打开日历之前通过select选择的总共要显示的月数）.

**Comment by mhxy13867806343** [comment]
@zymseo 我试下，谢谢@！

**Comment by mhxy13867806343** [comment]
@zymseo 我先关闭这个问题了！
